/**
 * Build Script - CSS Concatenation & Asset Optimization
 * Combines all CSS files into a single bundle to eliminate @import waterfall
 */

const fs = require('fs');
const path = require('path');

const CSS_DIR = path.join(__dirname, 'css');
const DIST_DIR = path.join(__dirname, 'dist');

// CSS files in dependency order (matching main.css @import order)
const CSS_FILES = [
    // Base Styles (variables must be first as other files depend on them)
    'base/variables.css',
    'base/typography.css',
    'base/reset.css',
    'base/animations.css',
    // Component Styles
    'components/layout.css',
    'components/top-bar.css',
    'components/dock.css',
    'components/window.css',
    'components/app-grid.css',
    'components/context-menu.css',
    'components/terminal.css',
    'components/apps.css',
    'components/ui-elements.css',
    'components/dialog.css',
    // Responsive (must be last)
    'components/responsive.css'
];

function ensureDistDir() {
    if (!fs.existsSync(DIST_DIR)) {
        fs.mkdirSync(DIST_DIR, { recursive: true });
    }
}

function concatenateCSS() {
    console.log('📦 Concatenating CSS files...');
    
    let bundledCSS = `/* ============================================
   BUNDLED CSS - Generated by build.js
   Do not edit directly - modify source files in /css
   ============================================ */\n\n`;

    for (const file of CSS_FILES) {
        const filePath = path.join(CSS_DIR, file);
        try {
            let content = fs.readFileSync(filePath, 'utf8');

            // Rewrite relative paths (fix for dist folder)
            // CSS files in /css/components/ refer to images as ../../images/
            // Bundled CSS in /dist/ refers to images as ../images/
            content = content.replace(/url\(['"]?(\.\.\/\.\.\/)([^'"]+)['"]?\)/g, "url('../$2')");
            
            bundledCSS += `/* === ${file} === */\n${content}\n\n`;
            console.log(`  ✓ ${file}`);
        } catch (err) {
            console.error(`  ✗ Error reading ${file}:`, err.message);
        }
    }

    return bundledCSS;
}

function minifyCSS(css) {
    // Basic CSS minification (for full minification, use clean-css-cli)
    return css
        .replace(/\/\*[\s\S]*?\*\//g, '')  // Remove comments
        .replace(/\s+/g, ' ')               // Collapse whitespace
        .replace(/\s*{\s*/g, '{')           // Remove space around {
        .replace(/\s*}\s*/g, '}')           // Remove space around }
        .replace(/\s*;\s*/g, ';')           // Remove space around ;
        .replace(/\s*:\s*/g, ':')           // Remove space around :
        .replace(/\s*,\s*/g, ',')           // Remove space around ,
        .trim();
}

function build() {
    console.log('\n🚀 Starting build...\n');
    
    ensureDistDir();
    
    // Concatenate CSS
    const bundledCSS = concatenateCSS();
    
    // Write unminified bundle (for development)
    const devPath = path.join(DIST_DIR, 'bundle.css');
    fs.writeFileSync(devPath, bundledCSS);
    console.log(`\n✓ Created ${devPath}`);
    
    // Write minified bundle (for production)
    const minifiedCSS = minifyCSS(bundledCSS);
    const prodPath = path.join(DIST_DIR, 'bundle.min.css');
    fs.writeFileSync(prodPath, minifiedCSS);
    console.log(`✓ Created ${prodPath}`);
    
    // Calculate size savings
    const originalSize = bundledCSS.length;
    const minifiedSize = minifiedCSS.length;
    const savings = ((1 - minifiedSize / originalSize) * 100).toFixed(1);
    
    console.log(`\n📊 Size: ${(originalSize / 1024).toFixed(1)}KB → ${(minifiedSize / 1024).toFixed(1)}KB (${savings}% reduction)\n`);
    console.log('✅ Build complete!\n');
}

build();
